[#parse-config]
= 配置解析

本章主要介绍一下配置文件的解析。

[#read-resource]
== 文件读取

对 Spring 框架比较了解的小伙伴可能都清楚，Spring 框架在处理文件读取时，提取了一个 `Resource`，而 `Resource` 接口又继承了 `InputStreamSource` 接口，这样只需要实现 `Resource` 接口，就可以实现在多种场景下的文件读取操作。 `Resource` 的类图如下：

plantuml::assets/diagrams/org.springframework.core.io.Resource.puml[{diagram_attr}]

相比 Spring 而言，MyBatis 对配置文件的处理就简单很多：直接使用一个工具类来读取。下面看具体源码，通常会使用 `Resources.getResourceAsStream("mybatis-config.xml")` 来读取配置文件。其实现如下：

.`org.apache.ibatis.io.Resources`
[{java_src_attr}]
----
include::{mybatis_src_basedir}/io/Resources.java[tag=getResourceAsStream-String,{java_src_attr}]
----

这是一个重载方法，它又交给了另外一个方法处理：

.`org.apache.ibatis.io.Resources`
[{java_src_attr}]
----
include::{mybatis_src_basedir}/io/Resources.java[tag=Resources,{java_src_attr}]

//...省略 N 行代码...

include::{mybatis_src_basedir}/io/Resources.java[tag=getResourceAsStream-ClassLoader-String,{java_src_attr}]
----

看方法可知，这里又委托给了 `ClassLoaderWrapper.getResourceAsStream` 方法来处理：

.`org.apache.ibatis.io.ClassLoaderWrapper`
[{java_src_attr}]
----
include::{mybatis_src_basedir}/io/ClassLoaderWrapper.java[tag=getResourceAsStream-String-ClassLoader,{java_src_attr}]
----

这又是一个重载方法。在继续之前，先拐个弯，看一下 `getClassLoaders` 方法：

.`org.apache.ibatis.io.ClassLoaderWrapper`
[{java_src_attr}]
----
include::{mybatis_src_basedir}/io/ClassLoaderWrapper.java[tag=getClassLoaders,{java_src_attr}]
----

从这里可知，可以指定 `ClassLoader`，否则就以这里出现的类加载器顺序来加载配置文件。再回到 `getResourceAsStream` 方法：

.`org.apache.ibatis.io.ClassLoaderWrapper`
[{java_src_attr}]
----
include::{mybatis_src_basedir}/io/ClassLoaderWrapper.java[tag=getResourceAsStream-String-ClassLoaders,{java_src_attr}]
----

这里就很简单：遍历 `ClassLoader` 对象列表，通过 `getResourceAsStream` 方法来加载配置文件，成功即返回。


== XML 配置文件解析

[#propertiesElement]
=== `<properties>` 标签的处理

MyBatis 既可以在 XML 文件中配置参数，又可以通过 Properties 文件配置参数，示例如下：

[{java_src_attr}]
----
include::{turman_resource_basedir}/mybatis-config.xml[tag=properties,{xml_src_attr}]
----

参数配置的入口在 `XMLConfigBuilder` 中，具体代码如下：

.`org.apache.ibatis.builder.xml.XMLConfigBuilder`
[{java_src_attr}]
----
include::{mybatis_src_basedir}/builder/xml/XMLConfigBuilder.java[tag=propertiesElement,{java_src_attr}]
----

这里主要分为两步来处理：

==== XML 配置文件处理

对于 XML 的处理在 `XNode` 中，具体代码如下：

[#getChildrenAsProperties]
.`org.apache.ibatis.parsing.XNode`
[{java_src_attr}]
----
include::{mybatis_src_basedir}/parsing/XNode.java[tag=getChildrenAsProperties,{java_src_attr}]
----

处理也很简单，就是遍历子标签，取 `name` 和 `value` 属性，放在 `Properties` 对象中返回即可。

==== Properties 配置文件处理

Properties 配置文件可以通过 `<properties>` 的 `resource` 和 `url` 属性类配置，二者不能同时存在。所以，对其处理也分未两种情况：

. 对于 `resource` 属性的处理，与前面介绍的 <<read-resource>> 章节类似，这里不再赘述。
. 对于 `url` 属性的处理，在 `Resources.getUrlAsProperties` 方法中完成读取，就是直接建立连接，打开输入流，即可完成读取操作。

==== 小结

这里需要强调一点是：*Properties 配置文件的优先级更高，会覆盖 XML 配置文件的配置。*

[#settingsAsProperties]
=== `<settings>` 标签的处理

对 `<settings>` 标签的处理与 <<propertiesElement>> 中对 `resource` 属性值的处理类似，甚至直接重用了 <<getChildrenAsProperties, `XNode.getChildrenAsProperties`>> 方法。相关代码如下：

.`org.apache.ibatis.builder.xml.XMLConfigBuilder`
[{java_src_attr}]
----
include::{mybatis_src_basedir}/builder/xml/XMLConfigBuilder.java[tag=settingsAsProperties,{java_src_attr}]
----

从代码中，也可以清晰看出与 <<propertiesElement>> 的不同之处：检查设置项在 `Configuration` 类中是否存在对应的 Setter 方法。下面看看是怎么做到的？

简单来说是通过创建 `MetaClass` 对象来实现的。略过一些不必要的细节，直达核心：

.`org.apache.ibatis.reflection.DefaultReflectorFactory`
[{java_src_attr}]
----
include::{mybatis_src_basedir}/reflection/DefaultReflectorFactory.java[{java_src_attr}]
----

在 `DefaultReflectorFactory` 中保存了一个 `ConcurrentMap<Class<?>, Reflector>` 类型的变量，通过 `DefaultReflectorFactory.findForClass` 方法获取一个指定类型的反射结果时，会先从缓存中获取，如果没有则调用 `new Reflector(type)` 构建出缓存结果，然后在添加到变量中后返回结果集。

下面来看一下 `Reflector`。不需要看具体实现，只需要看属性及构造函数即可：

[#Reflector_fieldsAndConstructor]
.`org.apache.ibatis.reflection.Reflector`
[{java_src_attr}]
----
include::{mybatis_src_basedir}/reflection/Reflector.java[tag=fieldsAndConstructor,{java_src_attr}]
----

从这些代码可以看出： `Reflector` 在做出初始化时，在构造函数里，将指定类的相关信息，使用反射获取，然后缓存起来，以便后续可以更快地执行反射调用。

== XML Mapper 配置文件解析

== 注解 Mapper 解析

// plantuml::assets/diagrams/observer.puml[{diagram_attr}]

== 参考资料

. https://www.lifesailor.me/archives/2676.html[MySQL升级8.0的新故障，utf8mb4_0900_ai_ci是啥？^]
